# Generated by Django 2.1 on 2018-08-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
                ('Responsavel', models.CharField(blank=True, max_length=255)),
                ('Parentesco', models.CharField(blank=True, max_length=200)),
                ('Nascimento', models.DateField()),
                ('Sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=2)),
                ('Cadastro', models.DateField()),
                ('Inicio', models.DateField()),
                ('Termino', models.DateField(blank=True)),
                ('Agendamento', models.IntegerField()),
                ('Convenio', models.CharField(choices=[('UNIMED', 'UNIMED'), ('AGEMED', 'AGEMED'), ('ABEPOM', 'ABEPOM'), ('PARTICULAR', 'PARTICULAR'), ('LOCUS', 'LOCUS'), ('ELASE', 'ELASE'), ('CORTESIA', 'CORTESIA')], max_length=20)),
                ('Modalidade', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CASAL', 'Casal'), ('FAMILIA', 'Familia'), ('GRUPO', 'Grupo'), ('AVALIACAO', 'Avaliação')], max_length=20)),
                ('Celular', models.IntegerField(blank=True)),
                ('Whats', models.IntegerField(blank=True)),
                ('Fixo', models.IntegerField(blank=True)),
                ('Email', models.EmailField(max_length=40)),
                ('EstadoCivil', models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('VIUVO', 'Viúvo'), ('UNIAO-ESTAVEL', 'União Estável')], max_length=20)),
                ('Profissao', models.CharField(max_length=100)),
                ('Rua', models.CharField(max_length=255)),
                ('Numero', models.CharField(max_length=255)),
                ('Complemento', models.CharField(max_length=255)),
                ('Bairro', models.CharField(max_length=255)),
                ('Cidade', models.CharField(max_length=255)),
                ('Estado', models.CharField(max_length=2)),
                ('Observacao', models.TextField()),
            ],
            options={
                'verbose_name': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='terapeutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('Crp', models.IntegerField()),
                ('Senha', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Terapeutas',
            },
        ),
    ]
