# Generated by Django 2.1 on 2018-08-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientes',
            options={'verbose_name': 'Pacientes', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='terapeutas',
            options={'verbose_name': 'Terapeutas', 'verbose_name_plural': 'Terapeutas'},
        ),
        migrations.AlterField(
            model_name='terapeutas',
            name='Crp',
            field=models.CharField(max_length=5),
        ),
    ]
