# Generated by Django 2.1 on 2018-08-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20180812_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='Celular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='Fixo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='Parentesco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='Responsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='Termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='Whats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
