# Generated by Django 2.1 on 2018-08-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20180812_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='Status',
            field=models.CharField(choices=[('ATENDIMENTO', 'Está sendo atendido'), ('LICENCA', 'Em licença'), ('ENCERRADO', 'Encerrado')], default='ATENDIMENTO', max_length=15),
        ),
    ]
