# Generated by Django 2.1 on 2018-08-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_pacientes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='Convenio',
            field=models.CharField(choices=[('UNIMED', 'UNIMED'), ('AGEMED', 'AGEMED'), ('ABEPOM', 'ABEPOM'), ('PARTICULAR', 'Particular'), ('LOCUS', 'LOCUS'), ('ELASE', 'ELASE'), ('CORTESIA', 'Cortesia')], max_length=20),
        ),
    ]
