# Generated by Django 2.1 on 2018-08-13 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20180813_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuarios',
            name='id_paciente',
        ),
        migrations.DeleteModel(
            name='prontuarios',
        ),
    ]
