# Generated by Django 2.1 on 2018-08-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20180813_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeutas',
            name='Username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='terapeutas',
            name='Nome',
            field=models.CharField(max_length=40),
        ),
    ]
