# Generated by Django 2.1 on 2018-08-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_auto_20180817_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapeutas',
            name='Senha',
            field=models.CharField(max_length=20),
        ),
    ]
