# Generated by Django 2.1 on 2018-08-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_auto_20180817_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='Email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='Observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
